# To use in local development:
# - Run `pip3 install pre-commit` (or `brew install pre-commit`)
# - In the project root directory (where this file resides) run: `pre-commit install`
# - Done! The below hooks should now automatically run before commit (where applicable).

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: no-commit-to-branch # Defaults to refuse commits to master
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-json
    - id: check-xml
    - id: check-yaml
    - id: detect-private-key
    - id: detect-aws-credentials
    - id: mixed-line-ending
    - id: end-of-file-fixer

- repo: https://github.com/anderseknert/pre-commit-opa
  rev: v1.4.0
  hooks:
  - id: opa-fmt
